library "alauda-cicd"
def language = "golang"
AlaudaPipeline {
    config = [
        agent: 'clang',
        folder: '.',
        scm: [
            credentials: 'alaudabot-gitlab'
        ],
        docker: [
            repository: "tdsql/percona-server-mongodb-15",
            credentials: "tdsql-harbor-b",
            context: "percona-server-mongodb-4.2",
            dockerfile: "percona-server-mongodb-4.2/Dockerfile.k8s",
            enabled: true,
            armBuild: false,
        ],
        sonar: [
            binding: "sonarqube",
            enabled: true
        ],
    ]
    env = [
        GO111MODULE: "on",
        GOPROXY: "https://athens.alauda.cn,https://goproxy.cn,direct",
        CGO_ENABLED: "0",
        GOOS: "linux",
    ]
}
